/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguacate.vista;

import static aguacate.modelo.NoobChain.UTXOs;
import static aguacate.modelo.NoobChain.genesisTransaction;
import static aguacate.modelo.NoobChain.walletA;
import aguacate.modelo.SalidaTransaccion;
import aguacate.modelo.Transaccion;
import aguacate.modelo.Usuario;
import aguacate.modelo.Wallet;
import co.edu.unisinu.tallerpro.abp.finanzas.Principal;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JoseP
 */
public class venPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form venPrincipal
     */
    public venPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idLogin = new javax.swing.JTextField();
        passLogin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        alertLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        bgPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setMaximumSize(new java.awt.Dimension(400, 500));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 6, 3));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AHORRO ESTUDIANTIL");

        idLogin.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        idLogin.setForeground(new java.awt.Color(204, 204, 204));
        idLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idLogin.setText("Por favor ingrese su ID Estudiantil");
        idLogin.setBorder(null);
        idLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idLoginMousePressed(evt);
            }
        });
        idLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLoginActionPerformed(evt);
            }
        });

        passLogin.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        passLogin.setForeground(new java.awt.Color(204, 204, 204));
        passLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passLogin.setText("Por favor ingrese su clave");
        passLogin.setBorder(null);
        passLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passLoginMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(246, 6, 3));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogin.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("ENTRAR");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        alertLabel.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        alertLabel.setForeground(new java.awt.Color(255, 0, 51));
        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(246, 6, 3));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnRegistrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("REGISTRARSE");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bgPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aguacate/imagenes/Untitled-1.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(idLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bgPhoto)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(idLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bgPhoto)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idLoginMouseClicked

    }//GEN-LAST:event_idLoginMouseClicked

    private void idLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idLoginMousePressed
        if (idLogin.getText().equals("Por favor ingrese su ID Estudiantil")){
            idLogin.setText("");
            idLogin.setForeground(Color.black);
        }
        if (passLogin.getText().equals("")){
            passLogin.setText("Por favor ingrese su clave");
            passLogin.setForeground(Color.gray);
        }
    }//GEN-LAST:event_idLoginMousePressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        if(idLogin.getText().isEmpty()){
            idLogin.setText("Por favor ingrese su ID Estudiantil");
            idLogin.setForeground(Color.gray);
            alertLabel.setText("Si usted no ingresa un ID no podra ingresar");
        }
        else if(idLogin.getText().equals("Por favor ingrese su ID Estudiantil")){
            alertLabel.setText("Si usted no ingresa un ID no podra ingresar");
        }
        if(passLogin.getText().isEmpty()){
            passLogin.setText("Por favor ingrese su clave");
            passLogin.setForeground(Color.gray);
            alertLabel.setText("Si usted no ingresa una clave no podra ingresar");
        }
        else if(passLogin.getText().equals("Por favor ingrese su clave")){
            alertLabel.setText("Si usted no ingresa una clave no podra ingresar");
        }
        else{
            String usuario;
            String password;
            usuario = idLogin.getText();
            password = passLogin.getText();
            if (Principal.usuarios.stream().filter(user -> user.id.equals(usuario)
                && user.password.equals(password)).findAny().isPresent()) {
                venInterna venPersonal = new venInterna();
                venPersonal.setLocationRelativeTo(null);
                venPersonal.setVisible(true);
                alertLabel.setText("Usted ha ingresado correctamente"); 
            }
            else{
                alertLabel.setText("Usuario incorrecto o desconocido");
            }
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        Wallet coinbase = new Wallet();
        String usuario;
        String password;
        if(idLogin.getText().isEmpty()){
            idLogin.setText("Por favor ingrese su ID Estudiantil");
            idLogin.setForeground(Color.gray);
            alertLabel.setText("Si usted no ingresa un ID no podra registrarse");
        }
        else if(idLogin.getText().equals("Por favor ingrese su ID Estudiantil")){
            alertLabel.setText("Si usted no ingresa un ID no podra registrarse");
        }
        else if(passLogin.getText().isEmpty()){
            passLogin.setText("Por favor ingrese su clave");
            passLogin.setForeground(Color.gray);
            alertLabel.setText("Si usted no ingresa una clave no podra registrarse");
        }
        else if(passLogin.getText().equals("Por favor ingrese su clave")){
            alertLabel.setText("Si usted no ingresa una clave no podra registrarse");
        }
        else{
            usuario = idLogin.getText();
            password = passLogin.getText();
            
            int balance = 10000;
            int deudas = 0;
            Usuario user = new Usuario();
            user.id = usuario;
            user.password = password;
            genesisTransaction = new Transaccion(coinbase.publicKey, user.getCartera().publicKey, 1000f, null);
            genesisTransaction.generateSignature(coinbase.privateKey);	 //manually sign the genesis transaction
            genesisTransaction.transactionId = "0"; //manually set the transaction id
            genesisTransaction.outputs.add(new SalidaTransaccion(genesisTransaction.reciepient, genesisTransaction.value, genesisTransaction.transactionId)); //manually add the Transactions Output
            UTXOs.put(genesisTransaction.outputs.get(0).id, genesisTransaction.outputs.get(0)); 
            // user.balance = balance;
            user.deudas = deudas;
            Principal.usuarios.add(user);
            alertLabel.setText("Su registro ha sido exitoso, por favor ingrese.");                  
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void passLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passLoginMouseClicked

    private void passLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passLoginMousePressed
        if (passLogin.getText().equals("Por favor ingrese su clave")){
            passLogin.setText("");
            passLogin.setForeground(Color.black);
        }
        if (idLogin.getText().equals("")){
            idLogin.setText("Por favor ingrese su ID Estudiantil");
            idLogin.setForeground(Color.black);
        }
    }//GEN-LAST:event_passLoginMousePressed

    private void idLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgPhoto;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JTextField idLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField passLogin;
    // End of variables declaration//GEN-END:variables
}
